name: Secrets Scan

permissions: {}
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "24 19 * * 5" # Every Friday at 19:24 UTC
  workflow_dispatch:

jobs:
  scan:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for full git history

      - name: Scan for Secrets with TruffleHog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          extra_args: --regex --entropy=False --results=all --format sarif --output results.sarif

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
