name: Secrets Scan

permissions: {}
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "24 19 * * 5" # Every Friday at 19:24 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog SS
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
