name: Secrets Scan

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "24 19 * * 5" # Every Friday at 19:24 UTC
  workflow_dispatch:

jobs:
  scan:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for full git history

      - name: Scan for Secrets with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
